import 'package:mobile_app/Models/BookModel.dart';

var categoryData = [
  {
    "icon": "Assets/Icons/plane.svg",
    "label": "Travel",
  },
  {
    "icon": "Assets/Icons/heart.svg",
    "label": "Romance",
  },
  {
    "icon": "Assets/Icons/star.svg",
    "label": "Fiction",
  },
  {
    "icon": "Assets/Icons/back.svg",
    "label": "History",
  },
];

var bookData = [
  BookModel(
    id: "1",
    title: "সাম্যবাদী",
    description: "",
    aboutAuthor: "This is my 1st android project",
    audioLen: "20",
    author: "কাজী নজরুল ইসলাম",
    coverUrl: "Assets/Images/সাম্যবাদী.png",
    rating: "8.6",
    category: "Documentary",
    numberofRating: 1120,
    price: 400,
    pdfPath: "Assets/273.pdf", // Correctly reference the PDF asset
  ),
  BookModel(
    id: "2",
    title: "বিজ্ঞান",
    description: "",
    aboutAuthor: "Details about the author",
    audioLen: "25",
    author: "রবীন্দ্রনাথ ঠাকুর",
    coverUrl: "Assets/Images/বিজ্ঞান.png",
    rating: "9.0",
    category: "Fiction",
    numberofRating: 890,
    price: 220,
    pdfPath: "Assets/584.pdf", // Ensure each book has its own PDF path
  ),
  BookModel(
    id: "3",
    title: "আরেক ফাল্গুন",
    description: "",
    aboutAuthor: "Information about the author",
    audioLen: "30",
    author: "জহির রায়হান",
    coverUrl: "Assets/Images/আরেক ফাল্গুন.png",
    rating: "4.8",
    category: "Romance",
    numberofRating: 15,
    price: 350,
    pdfPath: "Assets/sample-pdf.pdf", // Same here
  ),
  BookModel(
    id: "4",
    title: "কোরেল",
    description: "",
    aboutAuthor: "Information about the author",
    audioLen: "30",
    author: "শরতচন্দ্র চট্টোপাধ্যায়",
    coverUrl: "Assets/Images/কোরেল.png",
    rating: "4.8",
    category: "Romance",
    numberofRating: 15,
    price: 350,
    pdfPath: "Assets/4.pdf", // Same here
  ),
  BookModel(
    id: "5",
    title: "ছাড়পত্র",
    description: "",
    aboutAuthor: "Information about the author",
    audioLen: "30",
    author: " সুকান্ত ভট্টাচার্য",
    coverUrl: "Assets/Images/ছাড় পত্র.png",
    rating: "4.8",
    category: "Romance",
    numberofRating: 15,
    price: 350,
    pdfPath: "Assets/5.pdf", // Same here
  ),
  BookModel(
    id: "6",
    title: "দেয়ালের-দেশ",
    description: "",
    aboutAuthor: "Information about the author",
    audioLen: "30",
    author: "সৈয়দ শামসুল হক",
    coverUrl: "Assets/Images/দেয়ালের দেশ.png",
    rating: "4.8",
    category: "Romance",
    numberofRating: 15,
    price: 350,
    pdfPath: "Assets/6.pdf",
  ),
  BookModel(
    id: "7",
    title: "বিদ্যাসাগর-চরিত",
    description: "",
    aboutAuthor: "Information about the author",
    audioLen: "30",
    author: "ঈশ্বরচন্দ্র বিদ্যাসাগর",
    coverUrl: "Assets/Images/বিদ্যাসাগর.png",
    rating: "4.8",
    category: "Romance",
    numberofRating: 15,
    price: 350,
    pdfPath: "Assets/7.pdf",
  ),
  BookModel(
    id: "8",
    title: "শতবর্ষের ফেরারি ",
    description: "",
    aboutAuthor: "Information about the author",
    audioLen: "30",
    author: "বঙ্কিমচন্দ্র চট্টোপাধ্যায়",
    coverUrl: "Assets/Images/শতবর্ষের ফেরারি.png",
    rating: "4.8",
    category: "Romance",
    numberofRating: 15,
    price: 350,
    pdfPath: "Assets/8.pdf", // Same here
  ),
  BookModel(
    id: "9",
    title: "মহাপৃথিবী",
    description: "",
    aboutAuthor: "Information about the author",
    audioLen: "30",
    author: "জীবনানন্দ দাশ",
    coverUrl: "Assets/Images/মহা পৃথিবী.png",
    rating: "4.8",
    category: "Romance",
    numberofRating: 15,
    price: 350,
    pdfPath: "Assets/মহাপৃথিবী.pdf", // Same here
  ),
];
